FROM postgres:9.6
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# set up automatic restores
COPY postgis-scripts/1make-dbusers.sh Backups/restore-all.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/*.sh
COPY Backups /Backups
