FROM python:3.6
LABEL MAINTAINER="Brian H. Grant <brian@hackoregon.org> & M. Edward (Ed) Borasky <znmeb@znmeb.net>"
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

# add PostgreSQL client libraries
RUN apt-get update \
  && apt-get install -qqy --no-install-recommends \
    libpq-dev \
    postgresql-client \
  && apt-get clean

COPY /requirements.txt /code/
RUN pip install -r requirements.txt

RUN python
COPY . /code/
